apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:C
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: p5050/v1.0-release:1
        ports:
        - containerPort: 80
